### ISSUE TITLE
Could not convert HAR using library

### ISSUE THREAD

**Issue by naveenmandepudi** [zalando-incubator/transformer#75]
**Describe the bug**

I have placed HAR in examples folder of transformer folder.
Created py file with below:
`import transformer.transform as entry

with open("locustfile.py", "w") as f:
    entry.dump(f, "[./examples/1.har]")`
 and ran transformer library, below is the exception:
➜  transformer git:(master) ✗ python3.9 NaveenTest.py
Traceback (most recent call last):
  File "/Users/nmandepudi/transformer/NaveenTest.py", line 4, in <module>
    transformer.dump(f, ["./examples/1.har"])
  File "/Users/nmandepudi/transformer/transformer/transform.py", line 91, in dump
    file.writelines(
  File "/Users/nmandepudi/transformer/transformer/transform.py", line 135, in intersperse
    yield next(it)
  File "/Users/nmandepudi/transformer/transformer/transform.py", line 106, in _dump_as_lines
    scenarios = [
  File "/Users/nmandepudi/transformer/transformer/transform.py", line 107, in <listcomp>
    Scenario.from_path(
  File "/Users/nmandepudi/transformer/transformer/scenario.py", line 155, in from_path
    if path.is_dir():
AttributeError: 'str' object has no attribute 'is_dir'

**Transformer version**
Output of the command `transformer --version`.
1.3.0
**To Reproduce**
Steps and input files to reproduce the behavior:
1. Create the file "..."
create py file with below:
import transformer.transform as entry

with open("locustfile.py", "w") as f:
    entry.dump(f, "[./examples/1.har]")

2. Run Transformer with the arguments "..."
python3.9 <<above created file>>
3. See error

**Expected behavior**
HAR should be converted py file.

**Screenshots**
output on running the above py file:

➜  transformer git:(master) ✗ python3.9 NaveenTest.py
Traceback (most recent call last):
  File "/Users/nmandepudi/transformer/NaveenTest.py", line 4, in <module>
    transformer.dump(f, ["./examples/1.har"])
  File "/Users/nmandepudi/transformer/transformer/transform.py", line 91, in dump
    file.writelines(
  File "/Users/nmandepudi/transformer/transformer/transform.py", line 135, in intersperse
    yield next(it)
  File "/Users/nmandepudi/transformer/transformer/transform.py", line 106, in _dump_as_lines
    scenarios = [
  File "/Users/nmandepudi/transformer/transformer/transform.py", line 107, in <listcomp>
    Scenario.from_path(
  File "/Users/nmandepudi/transformer/transformer/scenario.py", line 155, in from_path
    if path.is_dir():
AttributeError: 'str' object has no attribute 'is_dir'

**Desktop (please complete the following information):**
 - OS: [e.g. Fedora, MacOS] MacOS
 - Version: [e.g. 22]

**Additional context**

**Comment by divinp** [comment]
Even I'm facing the same issue, can anyone let us know how to fix this issue?
